### ISSUE TITLE
Error on running - self._channel_range[ssid_obj.channel][ssid_name] = copy.deepcopy(ssid_obj)

### ISSUE THREAD

**Issue by johncarterofmars** [flashnuke/wifi-deauth#5]
Hello. I ran into this error when running the script. It counts down all the channels and then returns the error. It seems to be having a hard time compiling the list of SSIDs?
I am running this on Ubuntu 20.04 with an external USB capable of monitor mode. 
Any suggestions?
`$ sudo python3 wifi-deauth.py -i wlan1

 __      __ __  _____ __         _________                         __   __     
/  \    /  \__|/ ____\__|        \    __  \  _____ ______   __ ___/  |_|  |__  
\   \/\/   /  \   __\|  |  ______ |  |  \  \/ ___ \\  __ \ |  |  \   __|  |  \ 
 \        /|  ||  |  |  | /_____/ |  |__/  /\  ___/| |__\ \|  |  /|  | |   Y  \
  \__/\__/ |__||__|  |__|         |_______/  \____/|______/ ____/ |__| |___|__/ 

Make sure of the following:
1. You are running as root
2. You kill NetworkManager (manually or by passing --kill)
3. Your wireless adapter supports monitor mode (refer to docs)

Written by @flashnuke
================================================================================
[*] Setting up monitor mode...
[>] Running command -> 'sudo ip link set wlan1 down'
[>] Running command -> 'sudo iw wlan1 set monitor control'
[>] Running command -> 'sudo ip link set wlan1 up'
[*] Monitor mode was set up successfully
[*] Starting AP scan, please wait... (32 channels total)
[*] Scanning channel 140 (left -> 0))
Traceback (most recent call last):
  File "/home/usertools/wifi-deauth/wifi-deauth.py", line 270, in <module>
    attacker.run()
  File "/home/user/tools/wifi-deauth/wifi-deauth.py", line 209, in run
    self.target_ssid = self._start_initial_ap_scan()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/wifi-deauth/wifi-deauth.py", line 123, in _start_initial_ap_scan
    self._channel_range[ssid_obj.channel][ssid_name] = copy.deepcopy(ssid_obj)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 149`

**Comment by flashnuke** [comment]
sorry for the late reply
I've made a fix, please clone from this branch and try again: https://github.com/flashnuke/wifi-deauth/tree/fix/missing_channel
The change I've made is in this pull request https://github.com/flashnuke/wifi-deauth/pull/6
~~
It seems that scapy is picking up packets from channels that are supposedly "not supported" (they don't show up on your `iwlist {interface} channel` command output)
this could happen due to several reasons, the main suspect in this case imo is channel overlapping - the actual channel is not `149` as picked up by scapy, but another channel that overlaps this range

the fix I propose would set the SSID's channel as the current channel the interface is set at, when the channel shown in the packet (which is read by scapy) is not in the list of the supported channels

**Comment by flashnuke** [comment]
merged, pls lemme know if this issue persists
